[Interface]
PrivateKey = UMzChnC73+Q5N2jMqQe4AOvy8AoIaXNCi6H07e6U+FY=
Address = 10.104.0.208/32
DNS = 1.1.1.1, 8.8.8.8

[Peer]
PublicKey = fiaaxr+r00sgq9RByIekr7HrNh4UJbH1JU7Q1vc6gkc=
Endpoint = 51.75.145.220:443
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 25
