[Interface]
PrivateKey = uOnv9kEcXWah8ocLnfPI1MVCywo2I44ORr9ZoQ5iOUs=
Address = 10.104.5.191/32
DNS = 1.1.1.1, 8.8.8.8

[Peer]
PublicKey = YLaLJahXZ6NuASXQLPl0eUPVAypirpaLuuO7tZa2bmo=
Endpoint = 147.135.15.16:443
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 25
